# Generated by Django 3.2.3 on 2021-06-14 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecginformation',
            name='nurse',
            field=models.ForeignKey(default=1, limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='nurse_ecg_data', to='customUser.user', verbose_name='Doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecginformation',
            name='recorded_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 14, 9, 12, 31, 813124)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecginformation',
            name='doctor',
            field=models.ManyToManyField(limit_choices_to={'user_type': 1}, related_name='doctor_ecg_data', to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
    ]
