# Generated by Django 3.2.3 on 2021-06-14 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0002_auto_20210614_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecginformation',
            name='nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='nurse_ecg_data', to=settings.AUTH_USER_MODEL, verbose_name='Nurse'),
        ),
    ]
