# Generated by Django 3.2.3 on 2021-06-14 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0003_alter_ecginformation_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecginformation',
            name='nurse',
            field=models.ForeignKey(limit_choices_to={'user_type': 2}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nurse_ecg_data', to=settings.AUTH_USER_MODEL, verbose_name='Nurse'),
        ),
    ]
