# Generated by Django 3.2.3 on 2021-06-19 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0006_rename_doctor_ecginformation_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='doctor_considerations',
        ),
        migrations.CreateModel(
            name='DoctorConsideration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_considerations', models.TextField(verbose_name='Considerations of the Doctor')),
                ('is_considered', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 2}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Doctor')),
                ('ecg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='considerations', to='info.ecginformation', verbose_name='ECG Information')),
            ],
        ),
    ]
