# Generated by Django 3.2.3 on 2021-06-19 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('info', '0007_auto_20210619_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorconsideration',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'user_type': 1}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Doctor'),
        ),
    ]
